services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: courses
      MYSQL_USER: streamlit
      MYSQL_PASSWORD: streamlit
    ports:
      - "3307:3306"
    volumes:
      - ./data/mysql-data:/var/lib/mysql
    restart: always

  app:
    build:
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    restart: always
